### ISSUE TITLE
errore di battitura

### ISSUE THREAD

**Issue by getalseme** [ProfSchimd/5ia-2023-2024#1]
c'è un errore di battitura a riga 2 del file README.md a questo [link](https://github.com/ProfSchimd/5ia-2023-2024/tree/main/progetti/P001_TemaLibero), probabilmente andrà scritto "Il sito sarà composto di:" al posto di "Il sito sarà composto diL".

**Comment by getalseme** [comment]
ne ho registrato un altro alla fine del [Esempi di sito web
](https://github.com/ProfSchimd/5ia-2023-2024/tree/main/progetti/P001_TemaLibero#esempi-di-sito-web) nella sezione "Commercio elettronico".
"salvare per futuri acquisti." invece di "salvre per fututri acquisti."

**Comment by ProfSchimd** [comment]
Issue closed after latest commit.
